### ISSUE TITLE
Deprecation in Ember 3.3: Need to use ember-copy addon instead of Ember.copy

### ISSUE THREAD

**Issue by psbanka** [tomasbasham/ember-cli-adapter-pattern#2]
Ember introduced a new deprecation for 3.3: https://emberjs.com/deprecations/v3.x/#toc_ember-runtime-deprecate-copy-copyable

As Ember is no longer supporting the `Ember.copy` functionality, this code is deprecated:

https://github.com/tomasbasham/ember-cli-adapter-pattern/blob/master/addon/mixins/adaptable.js#L100

And we need to find another way to copy this object.

**Comment by tomasbasham** [comment]
I've instead opted to use `assign` which here has the same result as the original code
